# Generated by Django 5.0.1 on 2024-02-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='city_head_office',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='desired_placement_sections',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='geography_of_development',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='in_which_cities_shouldiopenafranchise',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='room_requirements',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='what_is_your_main_product',
        ),
    ]
