# Generated by Django 5.0.1 on 2024-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0005_franchise_allow_to_publish_requeststobuy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='start_investments',
            field=models.SmallIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
