# Generated by Django 5.0.1 on 2024-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_alter_region_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='sait_manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='allow_to_publish',
            field=models.BooleanField(default=False),
        ),
    ]
