# Generated by Django 5.0.1 on 2024-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0010_franchise_sait_manager_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='monthly_profit',
        ),
        migrations.AddField(
            model_name='franchise',
            name='average_check',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='royalties_monthly_coast',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
    ]
