# Generated by Django 5.0.1 on 2024-05-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0012_alter_locationmap_adygea_alter_locationmap_altai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='allow_to_publish',
            field=models.CharField(blank=True, choices=[('need_a_check', 'Нужна проверка'), ('published', 'Опубликована'), ('filled_in_incorrectly', 'Заполнена неверно')], max_length=100, null=True, verbose_name='Статус заявки'),
        ),
    ]
